services:
  - type: web
    name: hacking-night
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz prisma generate && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true
